---
# tasks file for deploy
 
    - name : create deploy
      shell :
              cmd : kubectl create deploy myid2 --image=httpd
      register : a
    - debug : 
              var : a
    - name : setup flannel cni
      shell :
              cmd : kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
    - name : get pods
      shell : 
              cmd : kubectl get pods
      register : b
    - debug : 
              var : b
    - name : expose deploy
      shell :
              cmd : kubectl expose deploy myid2 --port=80 --type=NodePort
